# -*- coding: utf-8 -*-
"""Phylogenetic Analysis and Protein Sequence Alignment Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjPyCEFZqphqm-ne6vBzWzI9lTkTjMyc
"""

from flask import Flask, render_template_string, request, jsonify

app = Flask(__name__)

essential_oils = {
    "lavender": {
        "properties": ["calming", "relaxing", "sleep-promoting"],
        "uses": ["aromatherapy", "topical application", "massage"]
    },
    "tea_tree": {
        "properties": ["antiseptic", "antibacterial", "antifungal"],
        "uses": ["skincare", "wound healing", "cleaning"]
    },
    "peppermint": {
        "properties": ["energizing", "refreshing", "pain-relieving"],
        "uses": ["aromatherapy", "topical application", "oral care"]
    }
}

html_template = """
<!DOCTYPE html>
<html>
<head>
    <title>Essential Oil Guide</title>
</head>
<body>
    <h1>Essential Oil Guide</h1>
    <form method="POST" action="/oil_info">
        <select name="oil">
            {% for oil in oils %}
                <option value="{{ oil }}">{{ oil }}</option>
            {% endfor %}
        </select>
        <button type="submit">Get Info</button>
    </form>
    <div id="oil-info"></div>

    <script>
        const form = document.querySelector('form');
        const oilInfoDiv = document.getElementById('oil-info');

        form.addEventListener('submit', async (event) => {
            event.preventDefault();
            const formData = new FormData(form);
            const response = await fetch('/oil_info', {
                method: 'POST',
                body: formData
            });
            const data = await response.json();
            oilInfoDiv.innerHTML = `
                <h2>Properties:</h2>
                <p>${data.properties.join(', ')}</p>
                <h2>Uses:</h2>
                <p>${data.uses.join(', ')}</p>
            `;
        });
    </script>
</body>
</html>
"""

@app.route('/')
def index():
    return render_template_string(html_template, oils=list(essential_oils.keys()))

@app.route('/oil_info', methods=['POST'])
def oil_info():
    selected_oil = request.form['oil']
    oil_data = essential_oils.get(selected_oil, {})
    return jsonify(oil_data)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000)